// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlyr7zzTOHG6vWSjCWfFQqh6VnNhJhMyA',
    appId: '1:718849493650:web:16030e223f051ead81f44b',
    messagingSenderId: '718849493650',
    projectId: 'chat-app-4020f',
    authDomain: 'chat-app-4020f.firebaseapp.com',
    storageBucket: 'chat-app-4020f.appspot.com',
    measurementId: 'G-EEJ0YQM85K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiACgev7jUUzvQXNRwN-0JcQlD5z8sV8w',
    appId: '1:718849493650:android:89e5a043e542689f81f44b',
    messagingSenderId: '718849493650',
    projectId: 'chat-app-4020f',
    storageBucket: 'chat-app-4020f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54-hKv_I2zWsNNaExOOy_cFgElZ4sUnw',
    appId: '1:718849493650:ios:844cff87cf26780981f44b',
    messagingSenderId: '718849493650',
    projectId: 'chat-app-4020f',
    storageBucket: 'chat-app-4020f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
